### PR TITLE
Update pr-check.yml to have 3.11 and 3.12-dev

### LINKED ISSUE #221: Add Python 3.11 and 3.12-dev to tests actions
We should add Python 3.11 and 3.12-dev here and see if all tests pass when submitting a PR: https://github.com/microsoft/vscode-pylint/blob/main/.github/workflows/pr-check.yml

### PR DESCRIPTION
**Pull request by bhagya-98**
related to issue : closes #221

### CODE REVIEW

**Comment by eleanorjboyd** [comment]
Hi! This looks like an old PR that is no longer needed - if that is true feel free to comment or close it yourself. Thanks

**Comment by karthiknadig** [comment]
@eleanorjboyd It looks like it just needed a rebase with main

**Comment by bhagya-98** [comment]
> @eleanorjboyd It looks like it just needed a rebase with main

@karthiknadig so i assume this PR is required right?

**Comment by karthiknadig** [comment]
Yes this looks good now.

**Review by anthonykim1 — APPROVED** [review]

**Review by eleanorjboyd — APPROVED** [review]

**Pull request merged**
