### PR TITLE
Change the flake8 version string in `readme.md` to be pip compatible

### PR DESCRIPTION
**Pull request by safiyat**
Changed the flake8 version string to be pip compatible.

### CODE REVIEW

**Comment by karthiknadig** [comment]
@safiyat This can break `nox` session to validate readme. Can you update that as well?

**Comment by safiyat** [comment]
> @safiyat This can break `nox` session to validate readme. Can you update that as well?

Done. Sorry I missed those changes to be made, earlier.

**Comment by safiyat** [comment]
> @safiyat please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="VoerEir AB"

**Comment by safiyat** [comment]
@karthiknadig could you please check now?

**Review by karthiknadig — APPROVED** [review]

**Review by anthonykim1 — APPROVED** [review]

**Pull request merged**
